[View in Colaboratory](https://colab.research.google.com/github/sharathsrini/Pytorch_Projects/blob/master/Pytorch_2.ipynb)

In [0]:
%matplotlib inline


What is PyTorch?
================

It’s a Python based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors


Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [0]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [7]:
x = torch.empty(5, 3)
print(x)

tensor([[5.9887e-36, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [5.2475e-08, 4.3915e-05, 1.0431e+21],
        [2.1364e-07, 1.0811e-05, 5.3484e+22],
        [2.1495e-04, 1.6427e-07, 0.0000e+00]])


Construct a randomly initialized matrix:



In [8]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7861, 0.4957, 0.5661],
        [0.0503, 0.2833, 0.3177],
        [0.5810, 0.2462, 0.8961],
        [0.2036, 0.5710, 0.4882],
        [0.2055, 0.2755, 0.6509]])


Construct a matrix filled zeros and of dtype long:



In [9]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [10]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [11]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.1096, -1.5039, -0.5360],
        [ 2.1765, -1.3788,  1.4773],
        [ 1.4406,  0.8891, -0.6370],
        [ 0.5336, -0.0101, -1.0568],
        [ 0.7381,  0.7453, -1.2020]])


Get its size:



In [12]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations

There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [13]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.3916, -0.5131, -0.0329],
        [ 2.8958, -0.6428,  1.9245],
        [ 2.0329,  1.2437,  0.1059],
        [ 1.3108,  0.4814, -0.4766],
        [ 1.5431,  1.3435, -0.2902]])


In [14]:
print(torch.add(x, y))

tensor([[-0.3916, -0.5131, -0.0329],
        [ 2.8958, -0.6428,  1.9245],
        [ 2.0329,  1.2437,  0.1059],
        [ 1.3108,  0.4814, -0.4766],
        [ 1.5431,  1.3435, -0.2902]])


Addition: providing an output tensor as argument



In [15]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.3916, -0.5131, -0.0329],
        [ 2.8958, -0.6428,  1.9245],
        [ 2.0329,  1.2437,  0.1059],
        [ 1.3108,  0.4814, -0.4766],
        [ 1.5431,  1.3435, -0.2902]])


Addition: in-place



In [16]:
# adds x to y
y.add_(x)
print(y)

tensor([[-0.3916, -0.5131, -0.0329],
        [ 2.8958, -0.6428,  1.9245],
        [ 2.0329,  1.2437,  0.1059],
        [ 1.3108,  0.4814, -0.4766],
        [ 1.5431,  1.3435, -0.2902]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [17]:
x

tensor([[-1.1096, -1.5039, -0.5360],
        [ 2.1765, -1.3788,  1.4773],
        [ 1.4406,  0.8891, -0.6370],
        [ 0.5336, -0.0101, -1.0568],
        [ 0.7381,  0.7453, -1.2020]])

In [18]:
print(x[:])

tensor([[-1.1096, -1.5039, -0.5360],
        [ 2.1765, -1.3788,  1.4773],
        [ 1.4406,  0.8891, -0.6370],
        [ 0.5336, -0.0101, -1.0568],
        [ 0.7381,  0.7453, -1.2020]])


In [19]:
y

tensor([[-0.3916, -0.5131, -0.0329],
        [ 2.8958, -0.6428,  1.9245],
        [ 2.0329,  1.2437,  0.1059],
        [ 1.3108,  0.4814, -0.4766],
        [ 1.5431,  1.3435, -0.2902]])

In [20]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [21]:
x = torch.randn(1)
print(x)
print(type(x.item()))

tensor([-1.4941])
<class 'float'>


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array




In [22]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [23]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [24]:
a.add_(15)
print(a)
print(b)

tensor([16., 16., 16., 16., 16.])
[16. 16. 16. 16. 16.]


Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically



In [25]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [26]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([-0.4941], device='cuda:0')
tensor([-0.4941], dtype=torch.float64)
